my_name = 'mahfuz'
print(my_name)
myfullname = 'AMUSA MAFUS OLAMILEKAN'
print(myfullname)
print(my_name.lower())
print(myfullname.upper())
print(myfullname.title())
#print(myname.capitalize())
print(myfullname.casefold())
print(myfullname.encode())
print(my_name.encode())
print(myfullname.expandtabs())
print(my_name.expandtabs())
print(myfullname.isalpha())
print(my_name.isalnum())
print(myfullname.isascii())
print(my_name.isdecimal())
print(myfullname.isdigit())
print(my_name.islower())
print(my_name.istitle())
print(myfullname.isspace())
print(myfullname.isupper())
